### ISSUE TITLE
game engine

### ISSUE THREAD

**Issue by dormantor** [atduskgreg/ofxaddons.com#135]
Hello,

I would like to share my OF addon I have been working on. It is a component-oriented game engine (not sure what category it belongs to).

The link: https://github.com/dormantor/ofxCogEngine 

Documentation will be updated continuously.

Best Regards,
DoDooo

**Comment by jamezilla** [comment]
Sorry it took so long for me to get to it. Added!

**Comment by dormantor** [comment]
I'm sorry but I still can't find it in the list

**Comment by dormantor** [comment]
Anybody home? It has been a year and I still don't have my library in your list!

**Comment by jamezilla** [comment]
First of all, this ticket has been closed since May 30th, 2016. Closed means "no one will ever look at it since it's closed". Reopening that ticket would've made sure someone was at least tracking it.

Second of all, this is a volunteer-run effort. There are people who are helping sort and tag the addons, but we're all busy. No one besides me has contributed any substantial code to this project since 2014. While I can appreciate your frustration, it did not make me very happy to come home from spending all day in the sun putting up a new installation to find this grumpy message. Please be considerate of the considerable time and effort we've put into providing this resource. We get nothing out of this except for the gratification of giving back to the community and the occasional usefulness of being able to use the index ourselves.

That said, there seems to be an issue with moving addons from an "incomplete" tag into the "addons" index. I think it's fixed at the moment, but there might be a persistence issue. Please keep an eye on it. **Reopen this ticket** if your addon disappears from the Game Engine category.
