### ISSUE TITLE
ofxPhyllotaxis

### ISSUE THREAD

**Issue by edap** [atduskgreg/ofxaddons.com#161]
https://github.com/edap/ofxPhyllotaxis
Addon that implements phyllotaxis alg.
Category: algorithms

**Comment by jamezilla** [comment]
Thanks for your patience. All set. We appreciate the contribution!

**Comment by edap** [comment]
Hey @jamezilla , thank you for the maintaining this website. Actually, there 2 other addons that are not listed in the website and I do not know why. The addons are:

https://github.com/edap/ofxSpaceColonization
Space Colonization algorithm implementation in openFrameworks
Category: algorithms

https://github.com/edap/ofxBranchesPrimitive
openFrameworks addon to create geometries composed by branches
Category: geometry

I know rails and ruby, let me know if I can help you with this website.

**Comment by jamezilla** [comment]
oh yah... if you want to help that'd be great! It's pretty much been a solo effort on the dev side since mid-2014. I just don't have time for it these days.

I think the biggest tasks we need to tackle are:
1. user-contributed categorization (self-service add to the site)
2. search
3. kill the front page (it's getting too big to load in a reasonable time)

Another interesting task might be to move the front-end to a client side render. It would simplify a lot of things, and the same API could feed tools like the project generator.

There's a lot of back end junk too if that's your cup of tea:

1. prune dead repos
1. roll up forks and call out more up-to-date forks
1. gather better meta-data about addons (detect travis/jenkins CI and see if they still build, etc)

Many, many more things... If any of it tickles your fancy let me know and we talk about approaches.
